[package]
name = "master"
version = "0.1.0"
authors = ["Alexey Erzyamkin <alexey.erzyamkin@outlook.com>"]
edition = "2018"

[dependencies]

actix-web = "3.3"
actix-files = "0.5"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.13", features = ["full"] }

shared = { path = "../shared" }