[package]
name = "master"
version = "0.1.0"
authors = ["Alexey Erzyamkin <alexey.erzyamkin@outlook.com>"]
edition = "2018"

[dependencies]

actix-web = "1.0"
actix-files = "0.1"
serde = "1.0"
serde_json = "1.0"
zip = "0.5"

shared = { path = "../shared" }