[package]
name = "worker"
version = "0.1.0"
authors = ["Alexey Erzyamkin <alexey.erzyamkin@outlook.com>"]
edition = "2018"

[dependencies]

serde = "1.0"
serde_json = "1.0"
reqwest = "0.9"
zip = "0.5"

shared = { path = "../shared" }